<a href="https://colab.research.google.com/github/Spasennyi4ert/inno_cource/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hi')

hi


a Импорт библиотеки NumPy

In [3]:
import numpy as np

b Создать массив из 10 нулей

In [4]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

c Создать массив из 10 единиц

In [5]:
on = np.ones(10)
on

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

d Создать массив из 10 пятерок

In [23]:
on*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

e Создать массив из целых чисел от 10 до 50

In [22]:
np.arange(10, 51, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

f Создать массив из четных чисел от 10 до 50

In [21]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

g Создать матрицу 3х3 с цислами от 0 до 8

In [20]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

h Создать единичную матрицу 3х3

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

i Использовать NumPy для генерации случайного числа от 0 до 1

In [18]:
np.random.rand(1)

array([0.14576613])

j Использовать NumPy для генерации массива из 25 случайных чисел

In [17]:
np.random.rand(25)

array([0.52635058, 0.15213858, 0.8935402 , 0.60190909, 0.70994571,
       0.63820352, 0.44227006, 0.98950767, 0.54270174, 0.67339838,
       0.39918672, 0.43042716, 0.20225618, 0.69356035, 0.55846435,
       0.68211612, 0.41465333, 0.92576817, 0.1014501 , 0.09536132,
       0.04728903, 0.68455441, 0.12532036, 0.59198686, 0.64599579])

k Создайте следующую матрицу используя функции библиотеки NumPy

In [16]:
np.arange(0, 1.01, 0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

l Матрица из условия задачи

In [25]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

m Написать код, который вернет следующую матрицу из стартовой

In [26]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

n Написать код обращения к элементу, который вернет значение 20 из матрицы mat

In [33]:
print(mat[mat==20])

[20]


o Написать код к матрице mat, который воспроизводит вывод

In [34]:
mat[0:3, 1].reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

p Написать код к матрице mat, который воспроизводит вывод

In [37]:
mat[4]

array([21, 22, 23, 24, 25])

r Написать код к матрице mat, который воспроизводит вывод

In [38]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

q Получить сумму всех значений в матрице mat

In [39]:
mat.sum()

325

s Получить стандартное отклонение в матрице mat

In [40]:
mat.std()

7.211102550927978

t Получить сумму значений в колонках матрицы mat

In [41]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])